// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecuIntegrator26.Infrastructure.Data;

#nullable disable

namespace SecuIntegrator26.Infrastructure.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20260103161324_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("SecuIntegrator26.Core.Entities.DailyClosingQuote", b =>
                {
                    b.Property<string>("StockCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Change")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ClosingPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("HighestPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OpeningPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("TradeValue")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TradeVolume")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("StockCode", "TradeDate");

                    b.ToTable("DailyClosingQuotes");
                });

            modelBuilder.Entity("SecuIntegrator26.Core.Entities.HolidayConfig", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHoliday")
                        .HasColumnType("INTEGER");

                    b.HasKey("Date");

                    b.ToTable("HolidayConfigs");
                });

            modelBuilder.Entity("SecuIntegrator26.Core.Entities.MonthlyRevenue", b =>
                {
                    b.Property<string>("StockCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearMonth")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MomChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RevenueCurrent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RevenueLastYear")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("YoyChange")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StockCode", "YearMonth");

                    b.ToTable("MonthlyRevenues");
                });

            modelBuilder.Entity("SecuIntegrator26.Core.Entities.StockSymbol", b =>
                {
                    b.Property<string>("StockCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("StockCode");

                    b.ToTable("StockSymbols");
                });

            modelBuilder.Entity("SecuIntegrator26.Core.Entities.DailyClosingQuote", b =>
                {
                    b.HasOne("SecuIntegrator26.Core.Entities.StockSymbol", "StockSymbol")
                        .WithMany()
                        .HasForeignKey("StockCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockSymbol");
                });

            modelBuilder.Entity("SecuIntegrator26.Core.Entities.MonthlyRevenue", b =>
                {
                    b.HasOne("SecuIntegrator26.Core.Entities.StockSymbol", "StockSymbol")
                        .WithMany()
                        .HasForeignKey("StockCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockSymbol");
                });
#pragma warning restore 612, 618
        }
    }
}
